server:
  port: 8081
  error:
    whitelabel:
      enabled: false


spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/project_db
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: Create_Project_SERVICE